name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.0
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - r-stringr
  - python=3.11
  - pip
  - pip:
    - plotly 
    - scikit-learn
    - numpy
    - psutil
    - toolz
    - matplotlib
    - dill
    - scipy
    - statsmodels
    - seaborn
    - pandas
    - partd
    - bokeh
    - dask
