name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - plotly 
    - scikit-learn
    - numpy
    - psutil
    - toolz
    - matplotlib
    - dill
    - scipy
    - statsmodels
    - seaborn
    - pandas
    - partd
    - bokeh
    - dask
